apiVersion: apps/v1
kind: Deployment
metadata:
  name: real-app
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: real-app
  template:
    metadata:
      labels:
        app: real-app
    spec:
      containers:
        - name: app
          image: 057773388128.dkr.ecr.eu-north-1.amazonaws.com/eks-real-app:latest
          ports:
            - containerPort: 3000
