apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: real-app
  namespace: demo
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - eks.mhecsproject.com
        - app.mhecsproject.com
      secretName: app-tls
  rules:
    - host: eks.mhecsproject.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: real-app
                port:
                  number: 80
    - host: app.mhecsproject.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: real-app
                port:
                  number: 80

