apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: real-app
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - demo
  selector:
    matchLabels:
      app: real-app
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
