apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"cert-manager.io/v1","kind":"ClusterIssuer","metadata":{"annotations":{},"name":"letsencrypt-prod"},"spec":{"acme":{"email":"hassan8347@yahoo.co.uk","privateKeySecretRef":{"name":"letsencrypt-prod-account-key"},"server":"https://acme-v02.api.letsencrypt.org/directory","solvers":[{"http01":{"ingress":{"class":"nginx"}}}]}}}
  generation: 1
  name: letsencrypt-prod
spec:
  acme:
    email: hassan8347@yahoo.co.uk
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: nginx
status:
  acme:
    lastPrivateKeyHash: gtO6IGlXkhEGdyxdRQ97mxgOrGhQOSOpFWmw1iohOvQ=
    lastRegisteredEmail: hassan8347@yahoo.co.uk
  conditions:
  - lastTransitionTime: "2026-01-20T15:57:45Z"
    message: The ACME account was registered with the ACME server
    observedGeneration: 1
    reason: ACMEAccountRegistered
    type: Ready
